### ISSUE TITLE
Property values for states that aren't active should be dimmed when in Microscope

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#175]
When a property has values set by states, it can be hard to work out what's going on. It would be much easier if all but the active state were dimmed out

_width@State1: 100
width@State2: 200_
**width@State3: 300**
_width@State4: 400_

**Comment by aaronkennedy** [comment]
So the case you show is pretty easy:

<img width="423" alt="screen shot 2018-05-31 at 10 50 12 pm" src="https://user-images.githubusercontent.com/813342/40783186-0d0fa4e8-6525-11e8-9737-3478c5033199.png">

But what should it look like if it is in *none* of those states, so that it is using the "default" width value. Should they all just be dimmed (so you can't see the current value at all)?
